PLATFORM_ISSUER = "https://amathuba.uct.ac.za/"
CLIENT_ID = "REPLACE_WITH_CLIENT_ID_FROM_AMATHUBA"
DEPLOYMENT_ID = "REPLACE_WITH_DEPLOYMENT_ID"

OIDC_AUTH_ENDPOINT = "https://YOUR_BRIGHTSPACE/oidc/auth"
OIDC_TOKEN_ENDPOINT = "https://YOUR_BRIGHTSPACE/auth/token"
PLATFORM_JWKS_URL = "https://YOUR_BRIGHTSPACE/.well-known/jwks.json"

TOOL_JWKS_URL = "https://YOUR_TOOL_DOMAIN/lti/jwks"
TOOL_REDIRECT_URI = "https://YOUR_TOOL_DOMAIN/lti/launch"
TOOL_INITIATE_LOGIN_URI = "https://YOUR_TOOL_DOMAIN/lti/login"

TOOL_PRIVATE_KEY_PEM = '''-----BEGIN RSA PRIVATE KEY-----
REPLACE_WITH_YOUR_PRIVATE_KEY_PEM
-----END RSA PRIVATE KEY-----'''
